language: go

go:
  - "1.12.x"
  - "1.13.x"
  - "1.14.x"
  - tip
sudo: false

git:
  depth: 1

before_install:
  - pip install --user codecov
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

install:

script:
  - go test ./...
  - cd tokenizer; go test -benchmem -bench .; cd ..
  - cd internal/dic; go test -benchmem -bench .; cd ../..

after_success:
  - |
    if [[ $TRAVIS_GO_VERSION = 1.14.x ]]
    then
      /bin/sh ./go-coverall.sh
    else
      echo skip coverage test, $TRAVIS_GO_VERSION
    fi
